baseURL = "https://g1en.site"
defaultContentLanguage = "zh"
languageCode = "zh-Hans"
title = "g1eny0ung's Blog"
theme = "dream"

enableGitInfo = true
enableRobotsTXT = true

hasCJKLanguage = true

# [services]
# [services.disqus]
# shortname = "g1eny0ung"
# [services.googleAnalytics]
# ID = "G-K6V0YY3HWS"

[markup]
[markup.goldmark.parser]
wrapStandAloneImageWithinParagraph = false
[markup.goldmark.parser.attribute]
block = true
[markup.goldmark.renderer]
unsafe = true
[markup.goldmark.extensions.passthrough]
enable = true
[markup.goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['\(', '\)']]
[markup.highlight]
noClasses = false

# [taxonomies]
# category = "categories"
# tag = "tags"
# series = "series"

[params]
lightTheme = "emerald"
darkTheme = "forest"

# backgroundImage = "img/global-background.jpg"
# backgroundImageDark = ""

images = ["img/global-background.jpg"]

author = "g1eny0ung"
description = "The life record of g1eny0ung is presented here."
avatar = "img/personal/avatar.jpg"
headerTitle = "g1eny0ung's Blog"
motto = "ä¸å…¶æ„Ÿæ…¨è·¯éš¾è¡Œï¼Œä¸å¦‚é©¬ä¸Šå‡ºå‘ã€‚"

# footerBottomText = ""

rss = true

# utterancesRepo = "g1eny0ung/g1eny0ung.github.io"

# valine = true
# LEANCLOUD_APP_ID = ""
# LEANCLOUD_APP_KEY = ""

# waline = true
# walineServer = ""

email = "g1enyy0ung@gmail.com"

siteStartYear = 2016

favicon = '<link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%2210 0 100 100%22><text y=%22.90em%22 font-size=%2290%22>ğŸŒ±</text></svg>"></link>'

# Syntax highlighting
customSyntaxHighlighting = true

# options
stickyNav = true
# reorderNavItems = ["about", "search", "rss", "posts", "categories", "tags"]
collapseNavItems = ["posts", "categories", "tags"]
# noDefaultSummaryCover = true
showTableOfContents = true
showSummaryCoverInPost = true
imageZoomableInPost = true
showPrevNextPost = true
# reorderShares = ["x", "facebook", "whatsapp"]

[params.navItems]

[params.advanced]
customCSS = ["css/custom.css"]
# customJS = []

[params.experimental]
jsDate = true
jsDateFormat = "yyyyå¹´MMæœˆddæ—¥"
# jsDateFormat = "yyyyå¹´MMæœˆddæ—¥ï¼Œcccc"
